# TANGRAM

In [1]:
import numpy as np

Aquest quadern conté els elements per resoldre puzzles de tangram com els del cinquè exemple del web arcprize.org

Comencem definint una funció que trobi quins quadrats 2x2 encaixen a l'ombra.

In [2]:
def fit_squares(grid):
  # Retorna una llista de graelles amb un quadrat de 2x2 que encaixa dins l'ombra.
  rows,cols=grid.shape

  square_list=[]
  for r in range(rows-1):
    for c in range(cols-1):
      if grid[r,c]!=0 and grid[r+1,c]!=0 and grid[r,c+1]!=0 and grid[r+1,c+1]!=0:
        h = np.zeros(grid.shape)
        h[r,c]=1
        h[r+1,c]=1
        h[r,c+1]=1
        h[r+1,c+1]=1
        square_list.append(h)

  return square_list

La funció següent troba les barres verticals de mida 3x1 que s'ajusten a l'ombra.

In [3]:
def fit_vertical_bars(grid):
  # Retorna una llista de graelles amb una barra de mida 3x1 dins l'ombra.
  rows,cols=grid.shape

  v_bar_list = []

  for r in range(rows-2):
    for c in range(cols):
      if grid[r,c]!=0 and grid[r+1,c]!=0 and grid[r+2,c]!=0:
        h = np.zeros(grid.shape)
        h[r,c]=1
        h[r+1,c]=1
        h[r+2,c]=1
        v_bar_list.append(h)

  return v_bar_list

A continuació definim la graella que s'ha de resoldre.

In [4]:
#Això és el segon exemple, que es pot resoldre sense peces horitzontals

graella_ombra = np.array([[0,0,0,0,0,0,0,0,0,0],
                          [0,1,1,1,1,1,1,0,0,0],
                          [0,1,1,1,1,1,1,0,0,0],
                          [0,0,0,1,0,0,1,0,0,0],
                          [0,0,0,0,1,1,1,0,0,0],
                          [0,0,0,0,1,1,1,0,0,0],
                          [0,0,0,0,1,0,0,0,0,0],
                          [0,0,0,0,0,0,0,0,0,0]
                          ])

print(graella_ombra)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0 0 0]
 [0 1 1 1 1 1 1 0 0 0]
 [0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [5]:
# Agrupam totes les peces dins una matriu 3D i la mostram

sq = fit_squares(graella_ombra)
vb = fit_vertical_bars(graella_ombra)
block_list = sq+vb

peces = np.array(block_list)
peces

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [6]:
import itertools

N = peces.shape[0] # nombre de peces candidates

for selector_de_peces in itertools.product([0,1], repeat=N): # cada peça pot ser-hi o no, generam totes les combinacions possibles
    suma_de_peces = np.sum(peces[np.array(selector_de_peces, dtype=bool)], axis=0)
    if  np.array_equal(suma_de_peces, graella_ombra):
      print("Hem trobat una solució")
      print(selector_de_peces)

Hem trobat una solució
(1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1)
